name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Build Library
      run: dotnet build UnrealIRCdRPC/UnrealIRCdRPC.csproj --configuration Release

    - name: Test
      run: dotnet test UnrealIRCdRPC.Tests/UnrealIRCdRPC.Tests.csproj --configuration Release --verbosity normal

    - name: Build Demo
      run: dotnet build Demo/Demo.csproj --configuration Release